<?php

namespace App\Console\Commands;

use Hihaho\RectorRules\Tests\Rector\NamingClasses\AddCommandSuffixRector\Source\BaseNotifyCommand;

final class NotifyUsers extends BaseNotifyCommand
{
}

-----
<?php

namespace App\Console\Commands;

use Hihaho\RectorRules\Tests\Rector\NamingClasses\AddCommandSuffixRector\Source\BaseNotifyCommand;

final class NotifyUsersCommand extends BaseNotifyCommand
{
}
