<?php declare(strict_types=1);

use SanderMuller\BoostCore\Config\BoostConfig;
use SanderMuller\BoostCore\Enums\Agent;
use SanderMuller\BoostCore\Enums\Tag;
use SanderMuller\BoostCore\Skills\Remote\RemoteSkillSource;

/**
 * boost-core configuration.
 *
 * Generated by `vendor/bin/boost install`. Re-run that command to update
 * agents/vendors interactively, or hand-edit this file. After changes
 * run `vendor/bin/boost sync`.
 *
 * Docs: https://github.com/sandermuller/boost-core
 */
return BoostConfig::configure()
    ->withTags([
        Tag::Github,
        Tag::Laravel,
        Tag::Php,
        Tag::Pest,
        'release-automation',
    ])
    ->withAgents([
        Agent::CLAUDE_CODE,
        Agent::COPILOT,
        Agent::CODEX,
    ])
    ->withAllowedVendors([
        'sandermuller/boost-core',
        'sandermuller/boost-skills',
        'sandermuller/package-boost-laravel',
        'sandermuller/package-boost-php',
    ])
    // Fills the boost-skills conventions tokens so vendor skills render this
    // project's specifics instead of needing host forks. Run `vendor/bin/boost
    // slots` to see available tokens and `boost validate` to check shapes.
    ->withConventions([
        'schema-version' => 1,
        'github' => [
            'owner' => 'hihaho',
            'repo' => 'rector-rules',
            'default_base_branch' => 'main',
        ],
        'testing' => [
            'backend_framework' => 'pest',
            'forbid' => ['dusk'],
        ],
        'codex' => [
            'invocation_mode' => 'plugin',
        ],
        'spec' => [
            'filename_pattern' => 'specs/{slug}.md',
        ],
        // Anonymization gate (boost-skills ^2.4): evaluate / final-verification
        // flag proprietary product domain leaking into this public package.
        // Policy prose lives in the guideline; the slot carries only the knobs.
        'fixtures' => [
            'anonymization' => [
                'guideline' => '.ai/guidelines/anonymize-test-fixtures.md',
                'scope' => ['tests/', 'src/', 'docs/', 'README.md'],
                'forbidden_terms' => ['Video', 'videos', 'caliper', 'adaptive'],
            ],
        ],
    ])
    // Pull rector-developer from peterfox/agent-skills (non-Composer upstream)
    // through the boost pipeline. Pinned to a commit SHA for reproducible
    // syncs (peterfox ships no release tags; a moving ref like `latest`/`main`
    // re-resolves every 24h and can drift silently). Bump the SHA to update.
    ->withRemoteSkills([
        RemoteSkillSource::githubPath('peterfox/agent-skills', 'e21f480242870c71db1f820a60e18468e51d1666', [
            'rector-developer' => 'rector-developer',
        ]),
    ])
    ->withDisabledEmitters([]);
